TPS = 30
TPS_DELTA = 1 / TPS
MAX_TICKS_PER_FRAME = 5

NETWORK_TICK_LIMIT = TPS_DELTA * 0.15
SEND_LIMIT = NETWORK_TICK_LIMIT * 0.5
RECV_LIMIT = NETWORK_TICK_LIMIT * 0.5

MAX_REDUNDANCY_TICKS = 10
SIMUL_DELAY_TICKS = 2
MAX_RESIM_TICKS = 10

MOVE_SPEED = 13.0
GRAVITY_RISE = 1.4
GRAVITY_FALL = 2.5
TERMINAL_VELOCITY = 32.0
JUMP_FORCE = -18.5
DASH_SPEED = 20
DASH_DURATION_TICKS = 10
ACCEL_X = 3.2
DECEL_X = 3.8
DASH_PLUNGE_SPEED = 32.0
MAX_JUMP_FORCE = -37.5
AIR_MOVE_SPEED = 6.25
AIR_ACCEL_X = 2.6
AIR_DECEL_X = 1.6
FAST_FALL_MULTIPLIER = 4.0
AIR_DRAG = 0.972
COYOTE_TICKS = 6
GROUND_TOLERANCE_PX = 2

# In accordance to tile size
PLAYER_WIDTH = 44
PLAYER_HEIGHT = 44
PLAYER_DUCK_HEIGHT = 22

PADDING_LEFT = 50
TEXT_CURSOR_WIDTH = 3
TEXT_INPUT_HOLD_DELAY = 400
TEXT_INPUT_HOLD_INTERVAL = 30
