TPS = 30
TPS_DELTA = 1 / TPS
MAX_TICKS_PER_FRAME = 5

NETWORK_TICK_LIMIT = TPS_DELTA * 0.15
SEND_LIMIT = NETWORK_TICK_LIMIT * 0.5
RECV_LIMIT = NETWORK_TICK_LIMIT * 0.5

MAX_REDUNDANCY_TICKS = 10
SIMUL_DELAY_TICKS = 2

MOVE_SPEED = 10.0
GRAVITY_RISE = 0.8
GRAVITY_FALL = 2.35
TERMINAL_VELOCITY = 45.0
JUMP_FORCE = -13.5
DASH_SPEED = 21.5
DASH_DURATION_TICKS = 10
ACCEL_X = 2.8
DECEL_X = 3.6
DASH_PLUNGE_SPEED = 45.0
MAX_JUMP_FORCE = -30.0
AIR_MOVE_SPEED = 4.25
AIR_ACCEL_X = 2.5
AIR_DECEL_X = 1.35
FAST_FALL_MULTIPLIER = 4.0
AIR_DRAG = 0.97

# In accordance to tile size
PLAYER_WIDTH = 44
PLAYER_HEIGHT = 44
PLAYER_DUCK_HEIGHT = 22

PADDING_LEFT = 50
TEXT_CURSOR_WIDTH = 3
TEXT_INPUT_HOLD_DELAY = 400
TEXT_INPUT_HOLD_INTERVAL = 30
